- charts/krakend/Chart.yaml
https://artifacthub.io/packages/helm/frinx-helm-charts/krakend
+ add an annotation for artifacthub because the security check doesn't find the image automatically
+ add the icon for the helm chart
> [krakend] Add annotation and icon

- charts/inventory/Chart.yaml
- charts/inventory/README.md
- charts/inventory/templates/deployment.yaml
- charts/inventory/values.yaml
> [inventory] Fix init container host name

- charts/uniflow/Chart.yaml
- charts/uniflow/README.md
- charts/uniflow/templates/deployment.yaml
- charts/uniflow/values.yaml
> [uniflow] Fix init container

- charts/uniconfig/Chart.yaml
- charts/uniconfig/templates/deployment.yaml
> [uniconfig] Increase probes time

- charts/krakend/Chart.yaml
- charts/krakend/README.md
- charts/krakend/values.yaml
> [krakend] Add default tenant id

- charts/frinx-frontend/Chart.yaml
- charts/frinx-frontend/README.md
- charts/frinx-frontend/values.yaml
> [frinx-frontend] Frinx frontend add default client

- charts/krakend/Chart.yaml
- charts/krakend/templates/_helpers.tpl
- charts/krakend/templates/deployment.yaml
- charts/krakend/templates/secret-azure-auth.yaml
> [krakend] Fix existingSecret in azureAuth

- charts/krakend/Chart.yaml
- charts/krakend/README.md
- charts/krakend/config/scripts/inventory_rbac.lua
- charts/krakend/config/scripts/unistore_rbac.lua
- charts/krakend/config/settings/workflow_proxy_settings.json
- charts/krakend/config/templates/unistore.tmpl
- charts/krakend/templates/deployment.yaml
- charts/krakend/values.yaml
> [krakend] Update RBAC config

- charts/sample-topology/Chart.yaml
- charts/sample-topology/README.md
- charts/sample-topology/templates/deployment.yaml
- charts/sample-topology/values.yaml
> [sample-topology] Add extraInitContainer and Bridge variables

- charts/worker/Chart.yaml
- charts/worker/README.md
- charts/worker/templates/deployment.yaml
- charts/worker/values.yaml
> [worker] Add UNICONFIG_URL_BASE env variable

- charts/uniconfig/Chart.yaml
- charts/uniconfig/README.md
- charts/uniconfig/templates/_helpers.tpl
- charts/uniconfig/templates/deployment.yaml
- charts/uniconfig/templates/secrets-storage.yaml
- charts/uniconfig/values.yaml
> [uniconfig] Add use storage existing secret option

- charts/frinx-grafana-configs/.helmignore
- charts/frinx-grafana-configs/Chart.yaml
- charts/frinx-grafana-configs/README.md
- charts/frinx-grafana-configs/config/db_cert_monitoring.json
- charts/frinx-grafana-configs/config/db_device_monitoring.json
- charts/frinx-grafana-configs/config/db_kube_monitoring.json
- charts/frinx-grafana-configs/config/db_loki_search.json
- charts/frinx-grafana-configs/config/db_node_monitoring.json
- charts/frinx-grafana-configs/config/db_uniconfig_monitoring.json
- charts/frinx-grafana-configs/templates/grafana-dashboards.yaml
- charts/frinx-grafana-configs/templates/grafana-datasources.yaml
- charts/frinx-grafana-configs/values.yaml
> [frinx-grafana-configs] Add grafana datasources and dashboards

- charts/inventory/Chart.yaml
- charts/inventory/README.md
- charts/inventory/values.yaml
> [inventory] Add capabilities

- charts/sample-topology/Chart.yaml
> [sample-topology] Update image version

- charts/demo-workflows/Chart.yaml
> [demo-workflows] Bump version

- charts/uniresource/Chart.yaml
- charts/uniresource/README.md
- charts/uniresource/templates/deployment.yaml
- charts/uniresource/values.yaml
> [uniresource] Update deployment

- charts/uniflow/Chart.yaml
- charts/uniflow/README.md
- charts/uniflow/templates/deployment.yaml
- charts/uniflow/values.yaml
> [uniflow] Update deployment

- charts/frinx-frontend/Chart.yaml
- charts/frinx-frontend/README.md
- charts/frinx-frontend/values.yaml
> [frinx-frontend] Add capabilities

- charts/frinx-grafana-configs/Chart.yaml
- charts/frinx-grafana-configs/README.md
- charts/frinx-grafana-configs/config/default.yaml
- charts/frinx-grafana-configs/templates/grafana-dashboards.yaml
- charts/frinx-grafana-configs/templates/grafana-datasources.yaml
- charts/frinx-grafana-configs/values.yaml
> [frinx-grafana-configs] Pass additional datasources to frinx-grafana-datasources

- charts/uniflow/Chart.yaml
- charts/uniflow/README.md
- charts/uniflow/templates/deployment.yaml
- charts/uniflow/values.yaml
> [uniflow] Fix schellar

- .github/workflows/lint-test.yaml
- charts/uniconfig/Chart.lock
- charts/uniconfig/Chart.yaml
- charts/uniconfig/README.md
- charts/uniconfig/templates/_configMaps.tpl
- charts/uniconfig/templates/configmap-lighty-uniconfig-config.yaml
- charts/uniconfig/templates/configmap-logback.yaml
- charts/uniconfig/templates/configmap-uniconfig-script.yaml
- charts/uniconfig/templates/deployment.yaml
- charts/uniconfig/templates/tests/test-connection.yaml
- charts/uniconfig/values.yaml
> [uniconfig] Fix traefik load balancer for local environment

- charts/uniflow/Chart.yaml
- charts/uniflow/configs/config.properties
Increase soft barriers for external storage to fix problem with policy filter workflow
> [uniflow] Increase soft barriers for external storage

- charts/frinx-frontend/Chart.yaml
- charts/frinx-frontend/README.md
- charts/frinx-frontend/values.yaml
- charts/frinx-machine/values.yaml
> [frinx-frontend] Frinx frontend add topology env

- charts/inventory/Chart.yaml
- charts/inventory/README.md
- charts/inventory/values.yaml
> [inventory] Update UNICONFIG_LIST_URL env variable

- charts/inventory/Chart.yaml
- charts/inventory/README.md
- charts/inventory/templates/deployment.yaml
- charts/inventory/values.yaml
> [inventory] Bump inventory service with device discovery

- charts/frinx-machine/Chart.yaml
- charts/frinx-machine/values.yaml
> [frinx-machine] Upgrade demo-workflows image

- charts/krakend/Chart.yaml
- charts/krakend/README.md
- charts/krakend/templates/ingress.yaml
- charts/krakend/values.yaml
> [krakend] Add support for nginx into ingress

- charts/uniresource/Chart.yaml
- charts/uniresource/templates/deployment.yaml
> [uniresource] Add emptyDir volume and fix initContainer

- charts/inventory/Chart.yaml
- charts/inventory/templates/deployment.yaml
> [inventory] Fix init container

- .github/workflows/lint.yaml
- charts/demo-workflows/Chart.yaml
- charts/demo-workflows/templates/deployment.yaml
> [demo-workflow] Fix deployment for read-only file system

- charts/worker/Chart.yaml
- charts/worker/templates/deployment.yaml
> [worker] Add Volume mount

- charts/frinx-machine/Chart.yaml
- charts/frinx-machine/values.yaml
> [frinx-machine] Fix topology discovery default name

- charts/uniconfig/Chart.yaml
- charts/uniconfig/templates/deployment.yaml
> [uniconfig] Fix cache permission problems

- charts/sample-topology/Chart.yaml
- charts/sample-topology/templates/deployment.yaml
Adding volume for all files because of problems with writing into schemas and scripts folders
> [sample-topology] Fix chart in non-root env

- charts/krakend/Chart.yaml
- charts/krakend/config/krakend.json
- charts/krakend/config/settings/resource_settings.json
- charts/krakend/config/settings/workflow_proxy_docs_settings.json
- charts/krakend/config/settings/workflow_proxy_settings.json
- charts/krakend/config/templates/resource.tmpl
- charts/krakend/templates/configmap-settings.yaml
- charts/krakend/templates/configmap-templates.yaml
- charts/krakend/templates/deployment.yaml
> [krakend] REST API renaming for uniflow, uniresource

- charts/resource-manager/Chart.yaml
- charts/resource-manager/README.md
- charts/resource-manager/templates/deployment.yaml
- charts/resource-manager/values.yaml
- charts/resource-manager/values.yaml.gotmpl
> [resource-manager] Update env variables

- charts/uniconfig/Chart.yaml
- charts/uniconfig/templates/_helpers.tpl
> [uniconfig] Update traefik deployment

- charts/workflow-manager/Chart.yaml
- charts/workflow-manager/README.md
- charts/workflow-manager/values.yaml
> [workflow-manager] Rename docker images

- .github/workflows/frinx-machine-latest-e2e.yaml
> E2E test on latest images

- charts/inventory/Chart.yaml
- charts/inventory/README.md
- charts/inventory/templates/deployment.yaml
- charts/inventory/templates/job-initDataSeed.yaml
- charts/inventory/values.yaml
> [inventory] Device discovery seed data

- charts/frinx-machine/Chart.yaml
- charts/frinx-machine/values.yaml
> [frinx-machine] Device discovery seed

- charts/frinx-frontend/Chart.yaml
- charts/frinx-frontend/values.yaml
> [frinx-frontend] Update frinx-frontend version

- .github/lint_test_config.yaml
- charts/frinx-arango-config/Chart.yaml
- charts/frinx-arango-config/README.md
- charts/frinx-arango-config/templates/arangodb-config.yaml
- charts/frinx-arango-config/templates/arangodb-secrets.yaml
- charts/frinx-arango-config/values.yaml
- charts/topology-discovery/Chart.yaml
- charts/topology-discovery/README.md
- charts/topology-discovery/templates/deployment.yaml
- charts/topology-discovery/values.yaml
> [frinx-arango-config, topology-discovery] Update env variables compatibility

- charts/krakend/Chart.yaml
- charts/krakend/config/krakend.json
> [krekend] Disable redirect

- charts/worker/Chart.yaml
- charts/worker/README.md
- charts/worker/templates/deployment.yaml
- charts/worker/values.yaml
> [worker] Fix for reading env variable

- charts/krakend/Chart.yaml
- charts/krakend/config/settings/topology_discovery_settings.json
> [krakend] Add Topology Discovery endpoints to KrakenD

- charts/frinx-frontend/Chart.yaml
- charts/frinx-frontend/README.md
- charts/frinx-frontend/values.yaml
- charts/krakend/Chart.yaml
- charts/krakend/README.md
- charts/krakend/config/krakend.json
- charts/krakend/templates/deployment.yaml
- charts/krakend/values.yaml
> [krakend,frinx-frontend] KrakenD Security improvements

- charts/inventory/Chart.yaml
- charts/inventory/templates/job-initDataSeed.yaml
> [inventory] Set unizonfig zone for seed scripts

- charts/inventory/Chart.yaml
- charts/inventory/templates/job-initDataSeed.yaml
> [inventory] Fix inventory-ready init container in seedJob

- charts/uniconfig/Chart.yaml
- charts/uniconfig/templates/deployment.yaml
Signed-off-by: Maros Marsalek <mmarsalek@frinx.io>
> [uniconfig] Use root user for copy-uniconfig-cache init step

- charts/krakend/Chart.yaml
- charts/krakend/config/settings/topology_discovery_settings.json
Signed-off-by: Maros Marsalek <mmarsalek@frinx.io>
> [krakend] Expose data/topology endpoint for topo disc

- charts/inventory/Chart.yaml
- charts/inventory/README.md
- charts/inventory/templates/deployment.yaml
- charts/inventory/values.yaml
> [inventory] Update Chart.yaml

- charts/frinx-frontend/Chart.yaml
- charts/frinx-frontend/README.md
- charts/frinx-frontend/values.yaml
> [frinx-frontend] Add INVENTORY_WS_URL environment variable

- .github/workflows/frinx-machine-lint-test.yaml
> Add PR title into notification

- charts/krakend/Chart.yaml
- charts/krakend/config/settings/topology_discovery_settings.json
> [krakend] Update endpoints for TD 0.0.5

- charts/krakend/Chart.yaml
- charts/krakend/README.md
- charts/krakend/templates/ingress.yaml
- charts/krakend/values.yaml
> [krakend] Add labels into ingress

- .github/renovate.json
- .github/workflows/lint-test.yaml
> Give renovate access to uc image

- charts/krakend/Chart.yaml
- charts/krakend/config/settings/topology_discovery_settings.json
> [krakend] Update endpoints for TD 0.0.6

- charts/inventory/Chart.yaml
- charts/inventory/README.md
- charts/inventory/values.yaml
> [inventory] Update database name

- charts/krakend/Chart.yaml
- charts/krakend/config/settings/topology_discovery_settings.json
> [krakend] Update endpoints for TD 0.0.7

- charts/krakend/Chart.yaml
- charts/krakend/templates/deployment.yaml
> [krakend] Update deployment in configMap change

- .github/workflows/frinx-machine-lint-test.yaml
- charts/frinx-machine/Chart.yaml
- effort to unite all cypress e2e tests related to frinx-frontend to one repository
- if testing specific deployment e.g. AKS (ephemeral) or service (prod or dev) we need to pick up specific set of tests
- repo with cypress tests is reorganized to support multiple config files in cypress/config folder
- `testkube create test`
will start cypress - we deliver to  cypress command line option using --executor-args
`--executor-args '--env environmentName=ephemeral'`
(which cause to start cypress like this: `npx cypress run --env environmentName=ephemeral`)
"ephemeral" is referring to `cypress/config` folder  files `cypress.ephemeral.js` and `ephemeral.json`
`ephemeral.json` contains cypress  environment  definition
`cypress.ephemeral.js` contains cypress configuration. 
In the cypress env. …
> testkube run tests - use --executor-args

- charts/frinx-frontend/Chart.yaml
- charts/frinx-frontend/templates/tests/test-connection.yaml
- charts/inventory/Chart.yaml
- charts/inventory/templates/tests/test-connection.yaml
- charts/krakend/Chart.yaml
- charts/krakend/templates/tests/test-connection.yaml
- charts/resource-manager/Chart.yaml
- charts/resource-manager/templates/tests/test-connection.yaml
- charts/sample-topology/Chart.yaml
- charts/sample-topology/templates/tests/test-connection.yaml
- charts/workflow-manager/Chart.yaml
- charts/workflow-manager/templates/tests/test-connection.yaml
> [frinx-frontend,inventory,krakend,resource-manager,sample-topology,workflow-manager] Fixed smoke test in non-root container

- charts/sample-topology/Chart.yaml
- charts/sample-topology/templates/tests/test-connection.yaml
> [sample-topology] Update test-connection.yaml

- charts/uniconfig/Chart.yaml
- charts/uniconfig/templates/deployment.yaml
> [uniconfig] Fix uniconfig in non-root environment

- charts/krakend/Chart.yaml
- charts/krakend/config/settings/topology_discovery_settings.json
> [krakend] Update endpoints for TD bgp ls

- charts/worker/Chart.yaml
- charts/worker/README.md
- charts/worker/templates/deployment.yaml
- charts/worker/values.yaml
> [worker] Add extraSecret option

- charts/krakend/Chart.yaml
- charts/krakend/README.md
- charts/krakend/config/krakend.json
- charts/krakend/config/templates/uniconfig.tmpl
- charts/krakend/templates/deployment.yaml
- charts/krakend/values.yaml
> [krakend] Add timeout option

- charts/sample-topology/Chart.yaml
- charts/sample-topology/templates/tests/test-connection.yaml
> [sample-topology] Fix smoke test with private image

- charts/frinx-arango-config/Chart.yaml
- charts/frinx-arango-config/README.md
- charts/frinx-arango-config/templates/arangodb-config.yaml
- charts/frinx-arango-config/values.yaml
> [frinx-arango-config] Update arangodeployment

- charts/worker/Chart.yaml
- charts/worker/README.md
- charts/worker/templates/deployment.yaml
- charts/worker/values.yaml
> [worker] Add option to store secrets as a file in pod

- charts/worker/Chart.yaml
- charts/worker/README.md
- charts/worker/templates/deployment.yaml
- charts/worker/values.yaml
> [worker] Store fileSecret target path to env variable

- charts/worker/Chart.yaml
- charts/worker/README.md
- charts/worker/values.yaml
> [worker] Manual for preparing secretFile

- charts/tftp/.helmignore
- charts/tftp/Chart.yaml
- charts/tftp/README.md
- charts/tftp/templates/NOTES.txt
- charts/tftp/templates/_helpers.tpl
- charts/tftp/templates/service.yaml
- charts/tftp/templates/serviceaccount.yaml
- charts/tftp/templates/statefulset.yaml
- charts/tftp/values.yaml
> [tftp] Add helm-chart

- charts/frinx-arango-config/Chart.yaml
- charts/frinx-arango-config/templates/arangodb-config.yaml
> [frinx-arango-config] Update arangodb-config.yaml

- charts/sample-topology/Chart.yaml
- charts/sample-topology/README.md
- charts/sample-topology/templates/_helpers.tpl
- charts/sample-topology/templates/configmap-devices.yaml
- charts/sample-topology/templates/deployment.yaml
- charts/sample-topology/templates/secret-repository.yaml
- charts/sample-topology/templates/service.yaml
- charts/sample-topology/templates/tests/test-connection.yaml
- charts/sample-topology/values.yaml
> [sample-topology] Add option to specify simulated devices

- charts/topology-discovery/Chart.yaml
- charts/topology-discovery/README.md
- charts/topology-discovery/templates/deployment.yaml
- charts/topology-discovery/values.yaml
> [topology-discovery] Fix importing to inventory

- charts/krakend/Chart.yaml
- charts/krakend/config/krakend.json
> [krakend] remove strict content_security_policy

- charts/frinx-frontend/Chart.yaml
- charts/frinx-frontend/templates/deployment.yaml
> [frinx-frontend] Fix permission problem

- charts/krakend/Chart.yaml
- charts/krakend/README.md
- charts/krakend/templates/service.yaml
- charts/krakend/values.yaml
> [krakend] Add support for nodeport

- charts/worker/Chart.yaml
- charts/worker/README.md
- charts/worker/templates/deployment.yaml
- charts/worker/values.yaml
> [workers] Add option to specify configmaps, workdir and commands 

- .github/lint_test_config.yaml
- charts/postgrest/.helmignore
- charts/postgrest/Chart.yaml
- charts/postgrest/README.md
- charts/postgrest/templates/NOTES.txt
- charts/postgrest/templates/_helpers.tpl
- charts/postgrest/templates/db-secret.yaml
- charts/postgrest/templates/deployment.yaml
- charts/postgrest/templates/hpa.yaml
- charts/postgrest/templates/ingress.yaml
- charts/postgrest/templates/service.yaml
- charts/postgrest/templates/serviceaccount.yaml
- charts/postgrest/templates/tests/test-connection.yaml
- charts/postgrest/values.yaml
> [postgrest] Add helm chart

- charts/workflow-manager/Chart.yaml
- charts/workflow-manager/README.md
- charts/workflow-manager/templates/ingress.yaml
- charts/workflow-manager/values.yaml
> [workflow-manager] Update ingress for workflow manager

- charts/frinx-grafana-configs/Chart.yaml
- charts/frinx-grafana-configs/config/db_loki_search.json
> [frinx-grafana-configs] Update db_loki_search.json

- charts/frinx-grafana-configs/Chart.yaml
- charts/frinx-grafana-configs/config/db_loki_uniconfig_device_logs.json
- charts/frinx-grafana-configs/config/db_loki_uniconfig_notification.json
> [frinx-grafana-configs] Create db_loki_uniconfig_notification.json

- charts/worker/Chart.yaml
- charts/worker/README.md
- charts/worker/templates/deployment.yaml
- charts/worker/values.yaml
> [worker] Add possibility to attach hostPath to pod

- charts/uniconfig/Chart.yaml
- charts/uniconfig/README.md
- charts/uniconfig/templates/deployment.yaml
- charts/uniconfig/values.yaml
> [uniconfig] Add a new Init stage to copy MIB files for SNMP support

- charts/krakend/Chart.yaml
- charts/krakend/config/partials/content_header.tmpl
- charts/krakend/config/partials/jwt_fake_config.tmpl
- charts/krakend/config/partials/uc_modifiers.tmpl
- charts/krakend/config/scripts/header_check.lua
- charts/krakend/config/templates/uniconfig.tmpl
- charts/krakend/templates/configmap-partials.yaml
- charts/krakend/templates/configmap-scripts.yaml
- add Content-Type via lua script only when it has no value
- setting Content-Type in modifier/martian is no longer necesary
Type: Bugfix
JIRA: DEP-682
> Set default Content-Type to application/json

- charts/topology-discovery/Chart.yaml
- charts/topology-discovery/README.md
- charts/topology-discovery/templates/NOTES.txt
- charts/topology-discovery/templates/_helpers.tpl
- charts/topology-discovery/templates/arangodb-secrets.yaml
- charts/topology-discovery/templates/deployment.yaml
- charts/topology-discovery/templates/ingress.yaml
- charts/topology-discovery/values.yaml
> [topology-discovery] refactoring for frinx-machine 6.0.0

- charts/workflow-manager/Chart.yaml
- charts/workflow-manager/README.md
- charts/workflow-manager/templates/_helpers.tpl
- charts/workflow-manager/templates/deployment.yaml
- charts/workflow-manager/templates/ingress.yaml
- charts/workflow-manager/templates/postgres-schellar-secrets.yaml
- charts/workflow-manager/templates/postgres-secrets.yaml
- charts/workflow-manager/templates/service.yaml
- charts/workflow-manager/templates/tests/test-connection.yaml
- charts/workflow-manager/values.yaml
> [workflow-manager] refactoring for frinx-machine 6.0.0

- charts/worker/Chart.yaml
- charts/worker/README.md
- charts/worker/templates/deployment.yaml
- charts/worker/values.yaml
> [worker] compatibility with frinx-machine 6.0.0

- charts/sample-topology/Chart.yaml
- charts/sample-topology/README.md
- charts/sample-topology/templates/ingress.yaml
- charts/sample-topology/values.yaml
> [sample-topology] compatibility with frinx-machine 6.0.0

- charts/cloud-native-pg/Chart.yaml
- charts/cloud-native-pg/README.md
- charts/cloud-native-pg/templates/helpers.tpl
- charts/cloud-native-pg/values.yaml
> [cloud-native-pg] compatibility with frinx-machine 6.0.0

- charts/frinx-arango-config/Chart.yaml
- charts/frinx-arango-config/README.md
- charts/frinx-arango-config/templates/arango-operator-secret.yaml
- charts/frinx-arango-config/templates/arangodb-config.yaml
- charts/frinx-arango-config/templates/arangodb-secrets.yaml
- charts/frinx-arango-config/values.yaml
> [frinx-arango-config] compatibility with frinx-machine 6.0.0

- .github/lint_test_config.yaml
- charts/resource-manager/Chart.yaml
- charts/resource-manager/README.md
- charts/resource-manager/templates/_helpers.tpl
- charts/resource-manager/templates/deployment.yaml
- charts/resource-manager/templates/ingress.yaml
- charts/resource-manager/templates/postgres-secrets.yaml
- charts/resource-manager/values.yaml
> [resource-manager] refactoring for resource-manager 6.0.0

- charts/frinx-arango-config/Chart.yaml
- charts/frinx-arango-config/templates/arangodb-config.yaml
> [frinx-arango-config] Upgrade ArangoDB datbase API version

- .github/frinx-machine_lint_test_config.yaml
- charts/frinx-machine/Chart.yaml
- charts/frinx-machine/README.md
- charts/frinx-machine/e2e-values.yaml
- charts/frinx-machine/ingress-values.yaml
- charts/frinx-machine/templates/db-persistance-secrets.yaml
- charts/frinx-machine/values.yaml
> [frinx-machine] Release of Frinx Machine 6.0.0

- charts/inventory/Chart.yaml
- charts/inventory/README.md
- charts/inventory/values.yaml
- charts/krakend/Chart.yaml
- charts/krakend/templates/deployment.yaml
> [krakend, inventory] Minor fixes in Frinx Machine 6.0.0 release

- charts/frinx-machine/Chart.yaml
> [frinx-machine] Update KrakenD and Inventory helm charts

- charts/worker/Chart.yaml
- charts/worker/templates/deployment.yaml
> [worker] Copy hidden files in initContainer

- charts/krakend/Chart.yaml
- charts/krakend/config/settings/workflow_manager_settings.json
> [krakend] Fix wrong conductor api url

- charts/frinx-machine/Chart.yaml
> [frinx-machine] Bump helm chart dependency versions

- charts/frinx-machine/Chart.yaml
> [frinx-machine] Increase inventory health-check start timeout

- .github/lint_test_config.yaml
- .github/workflows/linter.yaml
- charts/performance-monitor/.helmignore
- charts/performance-monitor/Chart.yaml
- charts/performance-monitor/README.md
- charts/performance-monitor/templates/NOTES.txt
- charts/performance-monitor/templates/_helpers.tpl
- charts/performance-monitor/templates/deployment.yaml
- charts/performance-monitor/templates/hpa.yaml
- charts/performance-monitor/templates/ingress.yaml
- charts/performance-monitor/templates/postgres-secrets.yaml
- charts/performance-monitor/templates/service.yaml
- charts/performance-monitor/templates/serviceaccount.yaml
- charts/performance-monitor/templates/tests/test-connection.yaml
- charts/performance-monitor/values.yaml
> [performance-monitor] Create performance-monitor helm chart

- charts/krakend/Chart.yaml
- charts/krakend/README.md
- charts/krakend/templates/configmap-nginx.yaml
- charts/krakend/values.yaml
> [krakend] Support krakend nginx with Azure AD idp

- charts/uniconfig/Chart.yaml
- charts/uniconfig/templates/deployment.yaml
- charts/uniconfig/values.yaml
> [uniconfig] ImagePullPolicy and resource limits for initContainers

- charts/worker/Chart.yaml
- charts/worker/README.md
- charts/worker/templates/deployment.yaml
- charts/worker/values.yaml
> [worker] Add more flexibility to worker chart

- charts/frinx-machine/Chart.yaml
- charts/frinx-machine/README.md
> [frinx-machine] Bump krakend and uniconfig versions

- .github/workflows/linter.yaml
- charts/performance-monitor/Chart.yaml
- charts/performance-monitor/README.md
- charts/performance-monitor/values.yaml
> [performance-monitor] remove latest tag from helm charts

- charts/performance-monitor/Chart.yaml
- charts/performance-monitor/templates/deployment.yaml
> [performance-monitor] Remove duplicated env from deployment template

- charts/swagger-ui/.helmignore
- charts/swagger-ui/Chart.yaml
- charts/swagger-ui/README.md
- charts/swagger-ui/README.md.gotmpl
- charts/swagger-ui/config/formatter.py
- charts/swagger-ui/templates/NOTES.txt
- charts/swagger-ui/templates/_helpers.tpl
- charts/swagger-ui/templates/configmap-filter.yaml
- charts/swagger-ui/templates/deployment.yaml
- charts/swagger-ui/templates/hpa.yaml
- charts/swagger-ui/templates/ingress.yaml
- charts/swagger-ui/templates/service.yaml
- charts/swagger-ui/templates/serviceaccount.yaml
- charts/swagger-ui/values.yaml
> [swagger-ui] Add swagger-ui helm chart

- charts/swagger-ui/Chart.yaml
- charts/swagger-ui/templates/deployment.yaml
> [swagger-ui] wait for server

- charts/workflow-manager/Chart.yaml
- charts/workflow-manager/templates/tests/test-connection.yaml
> [workflow-manager] Bump appVersion

- charts/frinx-arango-config/Chart.yaml
> [frinx-arango-config] Upgrade ArangoDB

- charts/worker/Chart.yaml
- charts/worker/README.md
- charts/worker/values.yaml
> [worker] Worker compatible with Frinx Machine 6.1

- charts/topology-discovery/Chart.yaml
- charts/topology-discovery/README.md
- charts/topology-discovery/README.md.gotmpl
- charts/topology-discovery/templates/deployment.yaml
- charts/topology-discovery/templates/service.yaml
- charts/topology-discovery/values.yaml
> [topology-discovery] Bump topology discovery

- charts/inventory/Chart.yaml
- charts/inventory/README.md
- charts/inventory/README.md.gotmpl
- charts/inventory/templates/deployment.yaml
- charts/inventory/values.yaml
> [inventory] Inventory 6.1

- charts/krakend/Chart.yaml
- charts/krakend/README.md
- charts/krakend/README.md.gotmpl
- charts/krakend/config/krakend.json
- charts/krakend/config/settings/performance_monitor_settings.json
- charts/krakend/config/settings/swagger_settings.json
- charts/krakend/config/templates/performance_monitor.tmpl
- charts/krakend/config/templates/swagger.tmpl
- charts/krakend/templates/configmap-nginx.yaml
- charts/krakend/templates/configmap-settings.yaml
- charts/krakend/templates/configmap-templates.yaml
- charts/krakend/templates/deployment.yaml
- charts/krakend/values.yaml
> [krakend] Krakend 6.1.1

- charts/uniconfig/Chart.yaml
- charts/uniconfig/README.md
- charts/uniconfig/README.md.gotmpl
- charts/uniconfig/templates/deployment.yaml
- charts/uniconfig/values.yaml
> [uniconfig] Uniconfig 6.1.1 and setting for Frinx Machine 6.1

- charts/frinx-frontend/Chart.yaml
- charts/frinx-frontend/README.md
- charts/frinx-frontend/values.yaml
> [frinx-frontend] Bump image versions to 6.1 and add/remove env variables

- charts/resource-manager/Chart.yaml
- charts/resource-manager/README.md
- charts/resource-manager/README.md.gotmpl
- charts/resource-manager/templates/deployment.yaml
- charts/resource-manager/templates/service.yaml
- charts/resource-manager/values.yaml
> [resource-manager] Add metrics port

- charts/frinx-machine/Chart.yaml
- charts/frinx-machine/README.md
- charts/frinx-machine/values.yaml
> [frinx-machine] Bump uniconfig version to 6.1.3

- .github/Dockerfile
- .github/workflows/build-custom-pyhton-image.yaml
> docker utilities image fixed

- charts/swagger-ui/Chart.yaml
- charts/swagger-ui/README.md
- charts/swagger-ui/templates/deployment.yaml
- charts/swagger-ui/values.yaml
> swagger-ui feature/dep 774

- charts/inventory/Chart.yaml
- charts/inventory/README.md
- charts/inventory/templates/deployment.yaml
- charts/inventory/templates/tests/test-connection.yaml
- charts/inventory/values.yaml
> [inventory] db_ready checks are performed using custom utilities image

- charts/worker/Chart.yaml
- charts/worker/README.md
- charts/worker/README.md.gotmpl
- charts/worker/templates/deployment.yaml
- charts/worker/values.yaml
> [worker] curls are performed using custom utilities image

- .github/lint_test_config.yaml
- charts/frinx-machine-operators/Chart.yaml
- charts/frinx-machine-operators/README.md
- charts/frinx-machine-operators/values.yaml
- required podmonitor/servicemonitor crds for monitoring
> [frinx-machine-operators] Add dependency for prometheus

- charts/krakend/Chart.yaml
- charts/krakend/README.md
- charts/krakend/templates/deployment.yaml
- charts/krakend/templates/service.yaml
- charts/krakend/templates/servicemonitor.yaml
- charts/krakend/values.yaml
- charts/resource-manager/Chart.yaml
- charts/resource-manager/README.md
- charts/resource-manager/templates/servicemonitor.yaml
- charts/resource-manager/values.yaml
- charts/uniconfig/Chart.yaml
- charts/uniconfig/README.md
- charts/uniconfig/templates/servicemonitor.yaml
- charts/uniconfig/values.yaml
- charts/workflow-manager/Chart.yaml
- charts/workflow-manager/README.md
- charts/workflow-manager/templates/conductor-servicemonitor.yaml
- charts/workflow-manager/templates/schellar-servicemonitor.yaml
- charts/workflow-manager/values.yaml
Change monitoring to metrics configuration
- move metrics ports from metrics section in krakend values.yaml to service section
> [krakend, resource-manager, uniconfig, workflow-manager]

- charts/frinx-machine-monitoring/Chart.yaml
- charts/frinx-machine-monitoring/values.yaml
> [frinx-machine-monitoring] Update promtail

- .github/workflows/lint-test.yaml
- charts/cloud-native-pg/Chart.yaml
- charts/cloud-native-pg/README.md
- charts/cloud-native-pg/README.md.gotmpl
- charts/cloud-native-pg/templates/postgres-cluster.yaml
- charts/cloud-native-pg/values.yaml
> [cloud-native-pg] Refactor templating for cluster kind. 

- charts/uniconfig/Chart.yaml
- charts/uniconfig/README.md
- charts/uniconfig/templates/deployment.yaml
> [uniconfig] Release for version 7.0
